<Project>
  <PropertyGroup>
    <LangVersion>latestMajor</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Company>Glass</Company>
    <Product>Glass</Product>
  </PropertyGroup>

</Project>
